FROM python:3.11
WORKDIR /app

# Copiar requirements desde el nivel raíz del servicio
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar el contenido de la carpeta app (donde está manage.py)
COPY app/ .

ENV DJANGO_SETTINGS_MODULE=blog_service.settings
EXPOSE 8001
CMD ["gunicorn", "blog_service.wsgi:application", "--bind", "0.0.0.0:8001"]
